from .pharm_original import extract_pharm_original_features_from_file, extract_pharm_original_features_from_img
from .pharm_revisited import extract_pharm_revisited_features_from_file, extract_pharm_revisited_features_from_img
